import { expiringSoon, planForDay } from './kitchen.js';
import { autoGeneratedList, predictBudgetOverrun } from './smart.js';
import { setupProgress } from './setup.js';
import {
  applyRecommendationBoost,
  resolveProductMode,
} from '../data/productModes.js';

const GOAL_ORDER = {
  plan: ['plan', 'cook', 'pantry', 'shop', 'log', 'targets'],
  shop: ['shop', 'pantry', 'plan', 'cook', 'log', 'targets'],
  pantry: ['pantry', 'plan', 'cook', 'shop', 'log', 'targets'],
};

export const contextualSetupStep = (app, steps) => {
  const mode = resolveProductMode(app.productMode);
  const order = mode.setupOrder || GOAL_ORDER[app.entryGoal] || GOAL_ORDER.plan;
  const dismissed = app.dismissedSetupSteps || [];
  return steps
    .filter((item) => !item.done && !dismissed.includes(item.id))
    .sort((a, b) => order.indexOf(a.id) - order.indexOf(b.id))[0] || null;
};

const actionForSetup = (item) => (
  item.id === 'pantry'
    ? { kind: 'pantry' }
    : { kind: 'tab', target: item.go }
);

const loggedDays = (app) => Object.values(app.log || {}).filter((entries) => entries.length).length;

export const guidanceFor = (app) => {
  const setup = setupProgress(app);
  const setupNext = contextualSetupStep(app, setup.steps);
  const expiring = expiringSoon(app.pantry || [], 3, app.day);
  const generated = autoGeneratedList(app);
  const budget = predictBudgetOverrun(app.shops || [], app.weeklyBudget, app.day);
  const todayPlan = planForDay(app.plan || {}, app.day);
  const plannedMeals = Object.values(todayPlan).filter(Boolean).length;
  const days = loggedDays(app);
  const items = [];

  if ((app.remindersDue || []).length) {
    items.push({
      id: 'reminders',
      priority: 100,
      label: 'Due now',
      title: `${app.remindersDue.length} reminder${app.remindersDue.length === 1 ? '' : 's'} need attention`,
      reason: 'These are the only time-sensitive actions in your food routine right now.',
      evidence: `${app.remindersDue.length} due today`,
      actionLabel: 'Review reminders',
      action: { kind: 'profile' },
      tone: 'warn',
    });
  }

  if (expiring.length) {
    const names = expiring.slice(0, 2).map((item) => item.name).join(' and ');
    items.push({
      id: 'expiry',
      priority: 95,
      label: 'Use soon',
      title: `Use ${names.toLowerCase()} next`,
      reason: `${expiring.length === 1 ? 'It expires' : 'They expire'} within three days, so this is the clearest chance to prevent waste.`,
      evidence: `${expiring.length} pantry item${expiring.length === 1 ? '' : 's'} expiring`,
      actionLabel: 'Open pantry',
      action: { kind: 'pantry' },
      tone: 'warn',
    });
  }

  if (setupNext) {
    items.push({
      id: `setup-${setupNext.id}`,
      setupId: setupNext.id,
      priority: 90,
      label: `Unlock more · ${setup.done} of ${setup.total}`,
      title: setupNext.label,
      reason: setupNext.why,
      evidence: `${setup.total - setup.done} useful setup step${setup.total - setup.done === 1 ? '' : 's'} left`,
      actionLabel: setupNext.label,
      action: actionForSetup(setupNext),
    });
  }

  if (budget?.risk === 'over') {
    items.push({
      id: 'budget',
      priority: 88,
      label: 'Budget alert',
      title: `Projected £${budget.difference.toFixed(2)} over budget`,
      reason: budget.reason,
      evidence: `£${budget.spent.toFixed(2)} recorded this week`,
      actionLabel: 'Review spending',
      action: { kind: 'tab', target: 'shop' },
      tone: 'warn',
    });
  }

  if (!(app.entries || []).length && setupNext?.id !== 'log') {
    items.push({
      id: 'log-today',
      priority: 75,
      label: 'Diary',
      title: 'Log something you ate',
      reason: 'Today’s guidance, nutrition and progress stay blank until the diary has one real meal.',
      evidence: 'No food logged today',
      actionLabel: 'Open food diary',
      action: { kind: 'log' },
    });
  } else if ((app.proteinToday || 0) < (app.proteinGoal || 0) * 0.55) {
    const left = Math.max(0, Math.round((app.proteinGoal || 0) - (app.proteinToday || 0)));
    items.push({
      id: 'protein',
      priority: 62,
      label: 'Nutrition',
      title: `${left}g protein remains today`,
      reason: 'That is the largest useful gap against the targets you chose.',
      evidence: `${Math.round(app.proteinToday || 0)}g of ${Math.round(app.proteinGoal || 0)}g logged`,
      actionLabel: 'Find a meal',
      action: { kind: 'tab', target: 'recipes' },
    });
  }

  if (!plannedMeals && setupNext?.id !== 'plan') {
    items.push({
      id: 'plan',
      priority: 65,
      label: 'Meal plan',
      title: 'Choose your next meal',
      reason: 'A planned meal can become a shopping list with pantry ingredients already deducted.',
      evidence: 'Nothing planned for today',
      actionLabel: 'Run the week loop',
      action: { kind: 'weekLoop', target: 'plan' },
    });
  }

  if (generated.length) {
    items.push({
      id: 'restock',
      priority: 58,
      label: 'Restock',
      title: `${generated.length} item${generated.length === 1 ? '' : 's'} may need buying`,
      reason: 'This combines things marked low with repeat purchases that are due, excluding what is already listed.',
      evidence: `${generated.length} explainable prediction${generated.length === 1 ? '' : 's'}`,
      actionLabel: 'Review predictions',
      action: { kind: 'view', target: 'tools' },
    });
  }

  if (days >= 3) {
    items.push({
      id: 'review',
      priority: 45,
      label: 'Pattern ready',
      title: 'Review what your diary is showing',
      reason: 'There is now enough recorded history to compare recent food, spending and kitchen patterns.',
      evidence: `${days} logged day${days === 1 ? '' : 's'}`,
      actionLabel: 'See trends',
      action: { kind: 'view', target: 'review' },
    });
  }

  if (!items.length) {
    items.push({
      id: 'steady',
      priority: 1,
      label: 'On track',
      title: 'Nothing urgent needs your attention',
      reason: 'Your diary, plan and kitchen have no clear gap to fix. Review the evidence whenever you want a wider view.',
      evidence: `${days} logged day${days === 1 ? '' : 's'}`,
      actionLabel: 'See trends',
      action: { kind: 'view', target: 'review' },
    });
  }

  const ranked = items.sort((a, b) => b.priority - a.priority);
  return applyRecommendationBoost(ranked, app.productMode);
};
