import {
  addDays, dayStamp, spentInWeek, weekStart,
} from './kitchen.js';
import { shoppingNameKey } from './shopping.js';

const DAY_MS = 86400000;
const normalise = shoppingNameKey;
const dayDiff = (from, to) => Math.round(
  (new Date(`${to}T12:00:00`) - new Date(`${from}T12:00:00`)) / DAY_MS,
);
const median = (values) => {
  const sorted = [...values].sort((a, b) => a - b);
  const middle = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[middle] : Math.round((sorted[middle - 1] + sorted[middle]) / 2);
};

const validShops = (shops, today) => (shops || [])
  .filter((shop) => /^\d{4}-\d{2}-\d{2}$/.test(shop.date || '') && shop.date <= today)
  .sort((a, b) => a.date.localeCompare(b.date));

export const predictNextTrip = (shops = [], today = dayStamp()) => {
  const dates = [...new Set(validShops(shops, today).map((shop) => shop.date))];
  if (dates.length < 3) return null;
  const intervals = dates.slice(1).map((date, index) => dayDiff(dates[index], date)).filter((days) => days > 0 && days <= 60);
  if (intervals.length < 2) return null;
  const intervalDays = Math.max(1, median(intervals));
  let date = addDays(dates[dates.length - 1], intervalDays);
  while (date <= today) date = addDays(date, intervalDays);
  const spread = Math.max(...intervals) - Math.min(...intervals);
  return {
    date,
    intervalDays,
    evidence: dates.length,
    confidence: spread <= 2 ? 'strong' : spread <= 7 ? 'fair' : 'rough',
    reason: `Median gap across ${dates.length} recorded shopping days is ${intervalDays} days.`,
  };
};

export const predictLowStock = (shops = [], pantry = [], today = dayStamp()) => {
  const purchases = new Map();
  validShops(shops, today).forEach((shop) => {
    const seen = new Set();
    (shop.items || []).forEach((item) => {
      const key = normalise(item.name);
      if (!key || seen.has(key)) return;
      seen.add(key);
      const row = purchases.get(key) || { name: String(item.name || '').trim(), dates: [] };
      row.dates.push(shop.date);
      purchases.set(key, row);
    });
  });
  const pantryByName = new Map((pantry || []).map((item) => [normalise(item.name), item]));
  return [...purchases.values()].flatMap((row) => {
    const dates = [...new Set(row.dates)];
    if (dates.length < 2) return [];
    const intervals = dates.slice(1).map((date, index) => dayDiff(dates[index], date)).filter((days) => days > 0 && days <= 120);
    if (!intervals.length) return [];
    const intervalDays = Math.max(1, median(intervals));
    const dueDate = addDays(dates[dates.length - 1], intervalDays);
    if (dueDate > addDays(today, 7)) return [];
    const stocked = pantryByName.get(normalise(row.name));
    return [{
      name: row.name,
      times: dates.length,
      intervalDays,
      dueDate,
      overdueDays: Math.max(0, dayDiff(dueDate, today)),
      markedLow: Boolean(stocked?.low),
      reason: `Likely due from a ${intervalDays}-day purchase cadence across ${dates.length} shops; pantry quantity is not measured.`,
    }];
  }).sort((a, b) => a.dueDate.localeCompare(b.dueDate) || b.times - a.times || a.name.localeCompare(b.name));
};

export const predictBudgetOverrun = (shops = [], weeklyBudget = 0, today = dayStamp()) => {
  const budget = Math.max(0, Number(weeklyBudget) || 0);
  if (!budget) return null;
  const spent = spentInWeek(shops, today);
  const elapsed = Math.max(1, dayDiff(weekStart(today), today) + 1);
  const currentStart = weekStart(today);
  const previous = Array.from({ length: 4 }, (_, index) => {
    const start = addDays(currentStart, -(index + 1) * 7);
    const end = addDays(start, 6);
    const rows = (shops || []).filter((shop) => shop.date >= start && shop.date <= end);
    return rows.length ? rows.reduce((total, shop) => total + (Number(shop.total) || 0), 0) : null;
  }).filter((value) => value !== null);
  const typical = previous.length
    ? Math.round((previous.reduce((total, value) => total + value, 0) / previous.length) * 100) / 100
    : null;
  const pace = Math.round((spent / elapsed) * 7 * 100) / 100;
  const projected = typical === null ? pace : Math.max(spent, typical);
  const comparison = projected - budget;
  return {
    budget,
    spent,
    elapsedDays: elapsed,
    projected,
    difference: Math.round(comparison * 100) / 100,
    risk: comparison > 0 ? 'over' : 'within',
    typical,
    reason: typical === null
      ? spent
        ? `Projection extends ${elapsed} day${elapsed === 1 ? '' : 's'} of recorded spend across the week.`
        : 'No current or previous weekly spend is recorded, so the projection is zero.'
      : `Projection uses the average of ${previous.length} previous recorded week${previous.length === 1 ? '' : 's'}, never below what is already spent.`,
  };
};

export const autoGeneratedList = ({
  shops = [], pantry = [], shoppingList = [], today = dayStamp(),
} = {}) => {
  const existing = new Set((shoppingList || []).map((item) => normalise(item.name)));
  const rows = [];
  const add = (name, note, priority = 'normal') => {
    const key = normalise(name);
    if (!key || existing.has(key)) return;
    existing.add(key);
    rows.push({ name: String(name).trim(), qty: '', note, priority });
  };
  (pantry || []).filter((item) => item.low).forEach((item) =>
    add(item.name, 'Marked low in pantry', 'high'));
  predictLowStock(shops, pantry, today).forEach((item) =>
    add(item.name, `Predicted from ${item.intervalDays}-day purchase cadence`, item.overdueDays ? 'high' : 'normal'));
  return rows;
};

export const distanceMetres = (from, to) => {
  const lat1 = Number(from?.latitude);
  const lon1 = Number(from?.longitude);
  const lat2 = Number(to?.latitude);
  const lon2 = Number(to?.longitude);
  if (![lat1, lon1, lat2, lon2].every(Number.isFinite)) return Infinity;
  if (lat1 === lat2 && lon1 === lon2) return 0;
  const rad = (degrees) => degrees * (Math.PI / 180);
  const dLat = rad(lat2 - lat1);
  const dLon = rad(lon2 - lon1);
  const a = Math.sin(dLat / 2) ** 2
    + Math.cos(rad(lat1)) * Math.cos(rad(lat2)) * Math.sin(dLon / 2) ** 2;
  return Math.round(6371000 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)));
};
