import { describe, expect, it, vi } from 'vitest';
import {
  autoGeneratedList, distanceMetres, predictBudgetOverrun, predictLowStock,
  predictNextTrip,
} from '../src/lib/smart.js';
import { detectBarcodeImage, detectReceiptText } from '../src/lib/smart-capture.js';

const TODAY = '2026-07-28';
const shops = [
  { date: '2026-07-07', store: 'Tesco', total: 45, items: [{ name: 'Milk', price: 2 }] },
  { date: '2026-07-14', store: 'Tesco', total: 48, items: [{ name: 'Milk', price: 2.1 }] },
  { date: '2026-07-21', store: 'Tesco', total: 50, items: [{ name: 'Milk', price: 2.2 }] },
  { date: TODAY, store: 'Tesco', total: 60, items: [{ name: 'Bread', price: 1.5 }] },
];

describe('local predictions', () => {
  it('predicts the next trip from the median recorded interval', () => {
    expect(predictNextTrip(shops, TODAY)).toMatchObject({
      date: '2026-08-04',
      intervalDays: 7,
      evidence: 4,
    });
  });

  it('predicts low stock from repeat purchase cadence without claiming to know quantity', () => {
    const due = predictLowStock(shops, [], TODAY);
    expect(due[0]).toMatchObject({ name: 'Milk', times: 3, dueDate: '2026-07-28' });
    expect(due[0].reason).toMatch(/purchase cadence/i);
  });

  it('projects a weekly budget overrun from recorded pace', () => {
    expect(predictBudgetOverrun(shops, 50, TODAY)).toMatchObject({
      risk: 'over',
      budget: 50,
      spent: 60,
      projected: 60,
    });
  });

  it('generates a deduplicated list from marked-low and cadence-due products', () => {
    const list = autoGeneratedList({
      shops,
      pantry: [{ name: 'Eggs', low: true }, { name: 'Milk', low: false }],
      shoppingList: [{ name: 'Bread' }],
      today: TODAY,
    });
    expect(list.map((row) => row.name)).toEqual(['Eggs', 'Milk']);
    expect(list.every((row) => row.note)).toBe(true);
  });

  it('uses the shopping name matcher for singular and plural predictions', () => {
    const list = autoGeneratedList({
      shops,
      pantry: [{ name: 'Bananas', low: true }],
      shoppingList: [{ name: 'Banana' }],
      today: TODAY,
    });
    expect(list.map((row) => row.name)).toEqual(['Milk']);
  });

  it('measures distance for foreground geofence checks', () => {
    expect(distanceMetres({ latitude: 51.5, longitude: -0.1 }, { latitude: 51.5, longitude: -0.1 })).toBe(0);
    expect(distanceMetres({ latitude: 51.5, longitude: -0.1 }, { latitude: 51.501, longitude: -0.1 }))
      .toBeGreaterThan(100);
  });
});

describe('native image readers', () => {
  it('reads a barcode through the browser detector and closes the bitmap', async () => {
    const close = vi.fn();
    const createBitmap = vi.fn(async () => ({ close }));
    class Detector {
      static getSupportedFormats = async () => ['ean_13'];
      detect = async () => [{ rawValue: '5000108000015' }];
    }
    await expect(detectBarcodeImage({}, { Detector, createBitmap })).resolves.toBe('5000108000015');
    expect(close).toHaveBeenCalled();
  });

  it('joins text blocks from a native receipt OCR result', async () => {
    const close = vi.fn();
    class Detector {
      detect = async () => [{ rawValue: 'TESCO' }, { rawValue: 'MILK £2.00' }];
    }
    await expect(detectReceiptText({}, { Detector, createBitmap: async () => ({ close }) }))
      .resolves.toBe('TESCO\nMILK £2.00');
    expect(close).toHaveBeenCalled();
  });
});
