import { useState } from 'react';
import {
  Bell, CalendarClock, Image, ListPlus, MapPin, Mic, PackageSearch, ReceiptText,
  ScanBarcode, Sparkles, Trash2, TriangleAlert,
} from 'lucide-react';
import { useApp } from '../lib/store.jsx';
import {
  autoGeneratedList, predictBudgetOverrun, predictLowStock, predictNextTrip,
} from '../lib/smart.js';
import { captureSupport } from '../lib/smart-capture.js';
import { suggestedReminders } from '../lib/reminder-suggest.js';
import { gbp, prettyDate } from '../lib/utils.js';
import { Card, Pill, Toggle } from './ui.jsx';

const Capability = ({ Icon, title, status, children }) => (
  <Card className="!p-3">
    <div className="flex items-start justify-between gap-3">
      <div className="min-w-0">
        <p className="font-bold text-[0.84375rem] inline-flex items-center gap-1.5"><Icon size={15} /> {title}</p>
        <p className="mt-0.5 text-[0.75rem] font-semibold" style={{ color: 'var(--muted)' }}>{children}</p>
      </div>
      <Pill tone={status === 'Ready' ? 'good' : status === 'Partial' ? 'accent' : 'muted'}>{status}</Pill>
    </div>
  </Card>
);

function CaptureCard({ onOpenAssistant }) {
  const support = captureSupport();
  return (
    <div className="space-y-2.5">
      <Capability Icon={ScanBarcode} title="Barcode recognition" status={support.barcode ? 'Ready' : 'Fallback'}>
        Reads EAN/UPC barcodes from a camera image through the browser’s native detector. Manual entry remains available.
      </Capability>
      <Capability Icon={ReceiptText} title="OCR receipt scanning" status={support.receiptText ? 'Ready' : 'Fallback'}>
        Uses the browser’s native text detector when available, then checks parsed items against the printed total. Paste text elsewhere.
      </Capability>
      <Capability Icon={Image} title="Image recognition for food" status="Partial">
        The plate and shelf flows are an editable on-device catalogue demo. This build does not ship a vision model, so it does not claim to identify the actual pixels.
      </Capability>
      <Card className="!p-3">
        <div className="flex items-center justify-between gap-3">
          <div>
            <p className="font-bold text-[0.84375rem] inline-flex items-center gap-1.5"><Mic size={15} /> Voice assistant</p>
            <p className="mt-0.5 text-[0.75rem] font-semibold" style={{ color: 'var(--muted)' }}>
              {support.speech ? 'Ask the food coach by voice using browser speech recognition.' : 'Speech recognition is unavailable here; typed questions still work.'}
            </p>
          </div>
          <button
            onClick={onOpenAssistant}
            className="press shrink-0 rounded-xl border px-3 py-2 text-[0.75rem] font-extrabold"
            style={{ borderColor: 'var(--line)' }}
          >
            Open
          </button>
        </div>
      </Card>
    </div>
  );
}

function PredictionsCard({ trip, stock, budget }) {
  return (
    <div className="space-y-2.5">
      <Card>
        <p className="font-bold text-[0.875rem] inline-flex items-center gap-1.5"><CalendarClock size={15} /> Next shopping trip</p>
        {trip ? (
          <>
            <p className="mt-1 text-[1.375rem] font-extrabold">{prettyDate(trip.date)}</p>
            <p className="text-[0.75rem] font-semibold" style={{ color: 'var(--muted)' }}>
              {trip.reason} {trip.confidence} pattern.
            </p>
          </>
        ) : <p className="mt-1 text-[0.75rem] font-semibold" style={{ color: 'var(--muted)' }}>Three dated shopping trips are needed before Forq predicts another.</p>}
      </Card>
      <Card>
        <p className="font-bold text-[0.875rem] inline-flex items-center gap-1.5"><PackageSearch size={15} /> Predicted low stock</p>
        {stock.length ? (
          <div className="mt-2 space-y-2">
            {stock.slice(0, 6).map((item) => (
              <div key={item.name} className="rounded-xl p-2.5" style={{ background: 'var(--card-2)' }}>
                <div className="flex justify-between gap-3">
                  <p className="text-[0.8125rem] font-bold">{item.name}</p>
                  <Pill tone={item.overdueDays ? 'warn' : 'muted'}>{item.overdueDays ? `${item.overdueDays}d overdue` : `due ${item.dueDate.slice(8)}`}</Pill>
                </div>
                <p className="mt-0.5 text-[0.71875rem] font-semibold" style={{ color: 'var(--muted)' }}>{item.reason}</p>
              </div>
            ))}
          </div>
        ) : <p className="mt-1 text-[0.75rem] font-semibold" style={{ color: 'var(--muted)' }}>Nothing has enough repeat purchase history to predict yet.</p>}
      </Card>
      <Card>
        <p className="font-bold text-[0.875rem] inline-flex items-center gap-1.5"><TriangleAlert size={15} /> Budget overrun</p>
        {budget ? (
          <>
            <div className="mt-1 flex items-center gap-2">
              <p className="text-[1.375rem] font-extrabold">{gbp(budget.projected, { always: true })}</p>
              <Pill tone={budget.risk === 'over' ? 'warn' : 'good'}>{budget.risk === 'over' ? 'projected over' : 'within budget'}</Pill>
            </div>
            <p className="text-[0.75rem] font-semibold" style={{ color: 'var(--muted)' }}>
              {gbp(budget.spent, { always: true })} recorded against {gbp(budget.budget)}. {budget.reason}
            </p>
          </>
        ) : <p className="mt-1 text-[0.75rem] font-semibold" style={{ color: 'var(--muted)' }}>Set a weekly grocery budget to enable overrun prediction.</p>}
      </Card>
    </div>
  );
}

function SmartRemindersCard() {
  const app = useApp();
  const suggestions = suggestedReminders(app)
    .filter((suggestion) => !app.reminders.some((reminder) =>
      reminder.kind === suggestion.kind && reminder.times.join() === suggestion.times.join()));
  return (
    <Card>
      <p className="font-bold text-[0.875rem] inline-flex items-center gap-1.5"><Bell size={15} /> Smart reminders</p>
      {suggestions.length ? (
        <>
          <div className="mt-2 space-y-2">
            {suggestions.slice(0, 4).map((suggestion) => (
              <div key={suggestion.key} className="rounded-xl p-2.5" style={{ background: 'var(--card-2)' }}>
                <p className="text-[0.8125rem] font-bold">{suggestion.label} · {suggestion.times.join(', ')}</p>
                <p className="text-[0.71875rem] font-semibold" style={{ color: 'var(--muted)' }}>{suggestion.why}</p>
              </div>
            ))}
          </div>
          <button
            onClick={() => app.addSuggestedReminders(suggestions)}
            className="press mt-3 w-full rounded-xl py-2.5 text-[0.78125rem] font-extrabold"
            style={{ background: 'var(--accent)', color: 'var(--on-accent)' }}
          >
            Add {suggestions.length} smart reminder{suggestions.length === 1 ? '' : 's'}
          </button>
        </>
      ) : <p className="mt-1 text-[0.75rem] font-semibold" style={{ color: 'var(--muted)' }}>Suggestions appear once meal, exercise or weigh-in records show a repeat routine.</p>}
    </Card>
  );
}

function PlaceRemindersCard() {
  const app = useApp();
  const support = captureSupport();
  const [label, setLabel] = useState('Shopping list');
  const [status, setStatus] = useState('');

  const saveHere = () => {
    if (!support.geolocation) {
      setStatus('Geolocation is unavailable in this browser.');
      return;
    }
    setStatus('Finding your location…');
    navigator.geolocation.getCurrentPosition(
      ({ coords }) => {
        app.addPlaceReminder({
          label,
          latitude: coords.latitude,
          longitude: coords.longitude,
          radius: 200,
        });
        setStatus('Saved. Leave and re-enter this area while Forq is open to test it.');
      },
      () => setStatus('Location permission was not granted.'),
      { enableHighAccuracy: false, timeout: 10000 },
    );
  };

  return (
    <Card>
      <p className="font-bold text-[0.875rem] inline-flex items-center gap-1.5"><MapPin size={15} /> Foreground location reminder</p>
      <p className="mt-1 text-[0.75rem] font-semibold" style={{ color: 'var(--muted)' }}>
        Saves a 200m area on this device and watches for re-entry only while Forq is open and notifications are allowed. Background geofencing requires a native app and is not claimed here.
      </p>
      <div className="mt-3 flex gap-2">
        <input
          value={label}
          onChange={(event) => setLabel(event.target.value)}
          aria-label="Location reminder name"
          className="min-w-0 flex-1 rounded-xl border px-3 py-2 text-[0.8125rem] font-semibold outline-none"
          style={{ background: 'var(--card-2)', borderColor: 'var(--line)', color: 'var(--ink)' }}
        />
        <button
          onClick={saveHere}
          className="press rounded-xl border px-3 text-[0.75rem] font-extrabold"
          style={{ borderColor: 'var(--line)' }}
        >
          Save here
        </button>
      </div>
      {status && <p role="status" className="mt-2 text-[0.75rem] font-semibold">{status}</p>}
      {app.placeReminders.length > 0 && (
        <div className="mt-3 space-y-2">
          {app.placeReminders.map((place) => (
            <div key={place.id} className="flex items-center gap-2 rounded-xl p-2.5" style={{ background: 'var(--card-2)' }}>
              <div className="min-w-0 flex-1">
                <p className="text-[0.8125rem] font-bold truncate">{place.label}</p>
                <p className="text-[0.6875rem] font-semibold" style={{ color: 'var(--muted)' }}>{place.radius}m · while open</p>
              </div>
              <Toggle label={`${place.on ? 'Disable' : 'Enable'} ${place.label}`} on={place.on} onChange={() => app.togglePlaceReminder(place.id)} />
              <button onClick={() => app.removePlaceReminder(place.id)} aria-label={`Delete ${place.label}`} className="press p-1" style={{ color: 'var(--faint)' }}>
                <Trash2 size={14} />
              </button>
            </div>
          ))}
        </div>
      )}
    </Card>
  );
}

export default function SmartFeaturesPanel({ onOpenAssistant, onNavigate }) {
  const app = useApp();
  const trip = predictNextTrip(app.shops, app.day);
  const stock = predictLowStock(app.shops, app.pantry, app.day);
  const budget = predictBudgetOverrun(app.shops, app.weeklyBudget, app.day);
  const generated = autoGeneratedList(app);
  const [addedKey, setAddedKey] = useState('');
  const listKey = generated.map((item) => item.name).join('|');
  const added = Boolean(addedKey && (!listKey || addedKey === listKey));

  const addList = () => {
    if (added) {
      onNavigate?.('shop');
      return;
    }
    app.addToList(generated);
    setAddedKey(listKey);
  };

  return (
    <div className="px-5 pb-10 space-y-4">
      <Card>
        <p className="font-extrabold text-[0.9375rem] inline-flex items-center gap-1.5"><Sparkles size={16} /> Predictions & capture</p>
        <p className="mt-1 text-[0.75rem] font-semibold" style={{ color: 'var(--muted)' }}>
          Device features where the browser provides them; explainable predictions from your own records everywhere else.
        </p>
      </Card>
      <CaptureCard onOpenAssistant={onOpenAssistant} />
      <PredictionsCard trip={trip} stock={stock} budget={budget} />
      <Card>
        <p className="font-bold text-[0.875rem] inline-flex items-center gap-1.5"><ListPlus size={15} /> Auto-generated list</p>
        <p className="mt-1 text-[0.75rem] font-semibold" style={{ color: 'var(--muted)' }}>
          Combines pantry items marked low with products due from repeat purchase cadence, excluding anything already listed.
        </p>
        <button
          onClick={addList}
          disabled={(!generated.length && !added) || !app.householdAccess.shopping}
          className="press mt-3 w-full rounded-xl py-2.5 text-[0.78125rem] font-extrabold disabled:opacity-40"
          style={{ background: 'var(--accent)', color: 'var(--on-accent)' }}
        >
          {added
            ? 'Review shopping list'
            : !app.householdAccess.shopping
              ? 'Shopping permission is off'
              : generated.length ? `Add ${generated.length} items to shopping` : 'Nothing predicted yet'}
        </button>
      </Card>
      <SmartRemindersCard />
      <PlaceRemindersCard />
    </div>
  );
}
